### ISSUE TITLE
Please avoid the use of EUMM + Module::Build

### ISSUE THREAD

**Issue by karenetheridge** [xsawyerx/moosex-role-loggable#5]
There is no good usecase to ship a module with Module::Build in Build.PL and EUMM in Makefile.PL at the same time. Especially for Dist::Zilla-using modules, it is just as easy to generate a Makefile.PL as a Build.PL, and EUMM is in core for all perl versions (and will continue to be).  We (PTG) are trying to reduce the unnecessary use of Module::Build on the cpan.

For this distribution, it's a simple matter of simply removing the `[ModuleBuild]` line from dist.ini, as you are already using `[MakeMaker]` via `[@Basic]`.

See also: http://neilb.org/2015/05/18/two-build-files-considered-harmful.html

**Comment by xsawyerx** [comment]
Agreed. I wanted at one point to clean all of those up, but I was too tired.

Merged and releasing new version as we speak. :)
